spring:
  application: springbasic
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

server:
  port: 9090
  servlet:
    contextPath: /app

